[package]
name = "lc_interpreter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lc_core = { path = "../lc_core" }
anyhow = "1.0.79"
dyn-clone = "1.0.16"
